# Data parameters
data:
  raw_path: "data/traffic_data.csv"
  processed_path: "data/processed_traffic_data.csv"
  test_size: 0.2
  random_state: 42

# Model parameters
model:
  type: "RandomForestClassifier"
  random_state: 42
  param_grid:
    n_estimators: [50, 100, 200, 300]
    max_depth: [null, 10, 20, 30]
    min_samples_split: [2, 5, 10, 15]
    min_samples_leaf: [1, 2, 4]
  cv_splits: 5
  search_iterations: 10

# Feature engineering
features:
  numerical_features:
    - packet_size
    - bytes_sent
    - packet_size_mean
    - bytes_sent_sum
    - timestamp_seconds
    - hour
    - source_ip_int
    - dest_ip_int
    - packet_rate
  categorical_features:
    - protocol

# Paths for saving models and artifacts
paths:
  model_path: "models/congestion_model.pkl"
  scaler_path: "models/scaler.pkl"
  features_path: "models/X.pkl"

# Logging configuration
logging:
  log_path: "logs/traffic_analysis.log"
  level: "INFO"